FROM oven/bun:1.3.1

RUN apt-get update && apt-get install -y --no-install-recommends \
      curl ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /repo
COPY . .
WORKDIR /repo/server
RUN bun install
WORKDIR /repo
