// RFC-030 Wave 1B — Codex binary + schema digest gate (fail closed).
//
// Wave-0 decision: the gateway only ever drives Codex 0.144.0, verified
// two ways before any socket opens:
//   1. `codex --version` output must equal the pinned line exactly.
//   2. `codex app-server generate-json-schema --out <tmp>` regenerated by
//      THE SAME binary must hash (sorted-path concat sha256) to the pinned
//      digest.
// Any mismatch → throw with code `codex_gateway_baseline_mismatch`; the
// runtime refuses to boot the gateway. No "close enough" versions.

import { execFile } from "child_process";
import { createHash } from "crypto";
import { mkdtempSync, readdirSync, readFileSync, rmSync, statSync } from "fs";
import { tmpdir } from "os";
import { join } from "path";
import {
  PINNED_CODEX_VERSION_LINE,
  PINNED_SCHEMA_SHA256,
} from "./pinned";

export const BASELINE_MISMATCH_CODE = "codex_gateway_baseline_mismatch";

function execFileP(
  bin: string,
  args: string[],
  timeoutMs: number,
): Promise<{ stdout: string; stderr: string }> {
  return new Promise((resolve, reject) => {
    execFile(bin, args, { timeout: timeoutMs }, (err, stdout, stderr) => {
      if (err) reject(err);
      else resolve({ stdout: String(stdout), stderr: String(stderr) });
    });
  });
}

function baselineError(detail: string): Error {
  const e = new Error(
    `codex baseline mismatch — refusing to boot the gateway (fail closed): ${detail}. ` +
      `The gateway is pinned to '${PINNED_CODEX_VERSION_LINE}' with schema sha256 ${PINNED_SCHEMA_SHA256.slice(0, 12)}…`,
  );
  (e as Error & { code?: string }).code = BASELINE_MISMATCH_CODE;
  return e;
}

/** Recursively collect files under dir as POSIX-style RELATIVE paths, sorted. */
function collectFilesSorted(root: string): Array<{ full: string; rel: string }> {
  const out: Array<{ full: string; rel: string }> = [];
  const walk = (dir: string, relPrefix: string) => {
    for (const name of readdirSync(dir).sort()) {
      const full = join(dir, name);
      const rel = relPrefix ? `${relPrefix}/${name}` : name;
      if (statSync(full).isDirectory()) walk(full, rel);
      else out.push({ full, rel });
    }
  };
  walk(root, "");
  return out.sort((a, b) => (a.rel < b.rel ? -1 : a.rel > b.rel ? 1 : 0));
}

/** Deterministically stringify a JSON value with sorted object keys. */
function canonicalJson(v: unknown): string {
  if (Array.isArray(v)) return `[${v.map(canonicalJson).join(",")}]`;
  if (v !== null && typeof v === "object") {
    const entries = Object.entries(v as Record<string, unknown>)
      .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
      .map(([k, val]) => `${JSON.stringify(k)}:${canonicalJson(val)}`);
    return `{${entries.join(",")}}`;
  }
  return JSON.stringify(v);
}

/**
 * sha256 over an UNAMBIGUOUS encoding of the whole bundle (副指挥 P1-4):
 * for every file, sorted by relative path, the hash absorbs
 *
 *   relPath ++ NUL ++ decimal(byteLength(content)) ++ NUL ++ content
 *
 * Domain separation properties this buys over plain content concat:
 *   - RENAME/MOVE sensitivity: the relative path (POSIX separators) is
 *     part of the input, so `a.json` renamed to `b.json`, or moved into
 *     a subdirectory, changes the digest even with identical bytes.
 *   - BOUNDARY sensitivity: the explicit byte length prevents content
 *     from bleeding across file boundaries — {"ab","c"} can never hash
 *     equal to {"a","bc"}; NULs terminate the path/length fields (paths
 *     and decimal lengths cannot contain NUL, so the framing is
 *     injective).
 *
 * `.json` content is parsed and re-serialized canonically first: codex's
 * generator emits semantically identical bundles whose key order varies
 * run-to-run (verified against 0.144.0), so raw bytes are not stable but
 * the canonical form is. The byteLength framed is the length of the
 * canonical form actually hashed. Non-JSON files (if any) hash raw.
 */
export function digestSchemaBundle(dir: string): string {
  const h = createHash("sha256");
  for (const { full, rel } of collectFilesSorted(dir)) {
    const raw = readFileSync(full);
    let content: Buffer = raw;
    if (rel.endsWith(".json")) {
      try {
        content = Buffer.from(canonicalJson(JSON.parse(raw.toString("utf8"))), "utf8");
      } catch {
        // not actually JSON — hash raw bytes
      }
    }
    h.update(Buffer.from(rel, "utf8"));
    h.update(Buffer.from([0]));
    h.update(Buffer.from(String(content.byteLength), "utf8"));
    h.update(Buffer.from([0]));
    h.update(content);
  }
  return h.digest("hex");
}

/**
 * Run both checks against `binary`. Throws (fail closed) on any mismatch;
 * resolves with the verified {version, schemaSha256} on success.
 */
export async function assertCodexBaseline(
  binary = "codex",
  opts: { timeoutMs?: number } = {},
): Promise<{ version: string; schemaSha256: string }> {
  const timeoutMs = opts.timeoutMs ?? 30_000;

  // 1. exact version line
  let versionOut: string;
  try {
    versionOut = (await execFileP(binary, ["--version"], timeoutMs)).stdout.trim();
  } catch (e) {
    throw baselineError(`'${binary} --version' failed: ${(e as Error).message}`);
  }
  if (versionOut !== PINNED_CODEX_VERSION_LINE) {
    throw baselineError(`binary reports '${versionOut}', pinned '${PINNED_CODEX_VERSION_LINE}'`);
  }

  // 2. schema digest regenerated by the same binary
  const tmp = mkdtempSync(join(tmpdir(), "codex-schema-gate-"));
  try {
    try {
      await execFileP(binary, ["app-server", "generate-json-schema", "--out", tmp], timeoutMs);
    } catch (e) {
      throw baselineError(`schema generation failed: ${(e as Error).message}`);
    }
    const digest = digestSchemaBundle(tmp);
    if (digest !== PINNED_SCHEMA_SHA256) {
      throw baselineError(
        `schema digest ${digest.slice(0, 12)}… does not match pinned ${PINNED_SCHEMA_SHA256.slice(0, 12)}…`,
      );
    }
    return { version: versionOut, schemaSha256: digest };
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
}
