// RFC-030 Wave 1B — Codex binary + schema digest gate (fail closed).
//
// Wave-0 decision: the gateway only ever drives Codex 0.144.0, verified
// two ways before any socket opens:
//   1. `codex --version` output must equal the pinned line exactly.
//   2. `codex app-server generate-json-schema --out <tmp>` regenerated by
//      THE SAME binary must hash (sorted-path concat sha256) to the pinned
//      digest.
// Any mismatch → throw with code `codex_gateway_baseline_mismatch`; the
// runtime refuses to boot the gateway. No "close enough" versions.

import { execFile } from "child_process";
import { createHash } from "crypto";
import { mkdtempSync, readdirSync, readFileSync, rmSync, statSync } from "fs";
import { tmpdir } from "os";
import { join } from "path";
import {
  assertCodexBinaryIdentity,
  resolveCodexBinaryIdentity,
  type CodexBinaryIdentity,
} from "./codex-binary";
import {
  PINNED_CODEX_VERSION_LINE,
  PINNED_SCHEMA_SHA256,
} from "./pinned";

export const BASELINE_MISMATCH_CODE = "codex_gateway_baseline_mismatch";

function execFileP(
  bin: string,
  args: string[],
  timeoutMs: number,
  env: NodeJS.ProcessEnv,
): Promise<{ stdout: string; stderr: string }> {
  return new Promise((resolve, reject) => {
    execFile(bin, args, { timeout: timeoutMs, env }, (err, stdout, stderr) => {
      if (err) reject(err);
      else resolve({ stdout: String(stdout), stderr: String(stderr) });
    });
  });
}

function baselineError(): Error {
  // No command output, candidate path, filesystem error, or observed digest
  // may reach a client/log surface through this exception.
  const e = new Error("codex baseline mismatch — refusing to boot the gateway (fail closed)");
  (e as Error & { code?: string }).code = BASELINE_MISMATCH_CODE;
  return e;
}

async function execVerifiedIdentity(
  identity: CodexBinaryIdentity,
  args: string[],
  timeoutMs: number,
  env: NodeJS.ProcessEnv,
): Promise<{ stdout: string; stderr: string }> {
  // Each of the two baseline executions is enclosed by identity checks.  The
  // post-check also runs after an exec failure so a replaced binary cannot be
  // misreported as an ordinary version/schema failure.
  assertCodexBinaryIdentity(identity);
  let result: { stdout: string; stderr: string } | null = null;
  let failed = false;
  try {
    result = await execFileP(identity.path, args, timeoutMs, env);
  } catch {
    failed = true;
  }
  assertCodexBinaryIdentity(identity);
  if (failed || result === null) throw baselineError();
  return result;
}

/** Recursively collect files under dir as POSIX-style RELATIVE paths, sorted. */
function collectFilesSorted(root: string): Array<{ full: string; rel: string }> {
  const out: Array<{ full: string; rel: string }> = [];
  const walk = (dir: string, relPrefix: string) => {
    for (const name of readdirSync(dir).sort()) {
      const full = join(dir, name);
      const rel = relPrefix ? `${relPrefix}/${name}` : name;
      if (statSync(full).isDirectory()) walk(full, rel);
      else out.push({ full, rel });
    }
  };
  walk(root, "");
  return out.sort((a, b) => (a.rel < b.rel ? -1 : a.rel > b.rel ? 1 : 0));
}

/** Deterministically stringify a JSON value with sorted object keys. */
function canonicalJson(v: unknown): string {
  if (Array.isArray(v)) return `[${v.map(canonicalJson).join(",")}]`;
  if (v !== null && typeof v === "object") {
    const entries = Object.entries(v as Record<string, unknown>)
      .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
      .map(([k, val]) => `${JSON.stringify(k)}:${canonicalJson(val)}`);
    return `{${entries.join(",")}}`;
  }
  return JSON.stringify(v);
}

/**
 * sha256 over an UNAMBIGUOUS encoding of the whole bundle (副指挥 P1-4):
 * for every file, sorted by relative path, the hash absorbs
 *
 *   relPath ++ NUL ++ decimal(byteLength(content)) ++ NUL ++ content
 *
 * Domain separation properties this buys over plain content concat:
 *   - RENAME/MOVE sensitivity: the relative path (POSIX separators) is
 *     part of the input, so `a.json` renamed to `b.json`, or moved into
 *     a subdirectory, changes the digest even with identical bytes.
 *   - BOUNDARY sensitivity: the explicit byte length prevents content
 *     from bleeding across file boundaries — {"ab","c"} can never hash
 *     equal to {"a","bc"}; NULs terminate the path/length fields (paths
 *     and decimal lengths cannot contain NUL, so the framing is
 *     injective).
 *
 * `.json` content is parsed and re-serialized canonically first: codex's
 * generator emits semantically identical bundles whose key order varies
 * run-to-run (verified against 0.144.0), so raw bytes are not stable but
 * the canonical form is. The byteLength framed is the length of the
 * canonical form actually hashed. Non-JSON files (if any) hash raw.
 */
export function digestSchemaBundle(dir: string): string {
  const h = createHash("sha256");
  for (const { full, rel } of collectFilesSorted(dir)) {
    const raw = readFileSync(full);
    let content: Buffer = raw;
    if (rel.endsWith(".json")) {
      try {
        content = Buffer.from(canonicalJson(JSON.parse(raw.toString("utf8"))), "utf8");
      } catch {
        // not actually JSON — hash raw bytes
      }
    }
    h.update(Buffer.from(rel, "utf8"));
    h.update(Buffer.from([0]));
    h.update(Buffer.from(String(content.byteLength), "utf8"));
    h.update(Buffer.from([0]));
    h.update(content);
  }
  return h.digest("hex");
}

/**
 * Run both checks against `binary`. Throws (fail closed) on any mismatch;
 * resolves with the verified {version, schemaSha256} on success.
 */
export async function assertCodexBaseline(
  binary = "codex",
  opts: {
    timeoutMs?: number;
    /** Source environment whose PATH resolves a bare binary name. */
    env?: NodeJS.ProcessEnv;
    /** Pre-resolved authoritative identity shared with an owned provider. */
    binaryIdentity?: CodexBinaryIdentity;
  } = {},
): Promise<{ version: string; schemaSha256: string }> {
  const timeoutMs = opts.timeoutMs ?? 30_000;
  const env = opts.env ?? process.env;
  const selectedIdentity = opts.binaryIdentity ?? resolveCodexBinaryIdentity(binary, { env });
  const identity = assertCodexBinaryIdentity(selectedIdentity);

  // 1. exact version line
  const versionOut = (
    await execVerifiedIdentity(identity, ["--version"], timeoutMs, env)
  ).stdout.trim();
  if (versionOut !== PINNED_CODEX_VERSION_LINE) {
    throw baselineError();
  }

  // 2. schema digest regenerated by the same binary
  let tmp: string;
  try {
    tmp = mkdtempSync(join(tmpdir(), "codex-schema-gate-"));
  } catch {
    throw baselineError();
  }

  let digest: string | null = null;
  let failure: unknown = null;
  try {
    await execVerifiedIdentity(
      identity,
      ["app-server", "generate-json-schema", "--out", tmp],
      timeoutMs,
      env,
    );
    try {
      digest = digestSchemaBundle(tmp);
    } catch {
      throw baselineError();
    }
    if (digest !== PINNED_SCHEMA_SHA256) throw baselineError();
  } catch (error) {
    failure = error;
  }
  try {
    rmSync(tmp, { recursive: true, force: true });
  } catch {
    if (failure === null) failure = baselineError();
  }
  if (failure !== null) throw failure;
  if (digest === null) throw baselineError();
  return { version: versionOut, schemaSha256: digest };
}
